project:
  type: website
  output-dir: docs

website:
  title: "Lawrence"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: Projects
      - href: Experience.qmd
        text: Experience

site-url: https://rsm-lal035.github.io/

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
